### PR TITLE
Add support for `tc` actions

### PR DESCRIPTION
**Pull request by aquarhead**
This work has been on my fork a couple month now, and I had a conversation with @alessandrod about this when he said he would like to add support for `tc` programs, that is also almost a month ago now... Forgive my laziness but anyway here I am ready to kick off this effort.

You can see in this PR that I've moved the `SkBuff` out of the `socket_filter` module, since `tc` programs use it for input as well, and (I believe) I followed existing example for other shared data structures for probes. I also plan to add a few more utility functions in `SkBuff` for example to test for specific protocol, and jump to packet data start - since IP and TCP header has some peculiar header length calculation that I spent quite a while to figure out. 

I picked the macro name `tc_action` because as I understand, there're also "classifiers" for `tc`, although I haven't really figure it out what they do or whether they're really different than "action" programs. As far as I remember, they have different return codes, so I believe it makes sense to separate them based on that.

Note with only this PR, the output ELF still cannot be loaded by `tc`. At least two problems that I've found workarounds:

- Strip `.text` section
- Rename `maps` section

As a complete working example, you can see [this project](https://github.com/aquarhead/protect-the-rabbit), and the workarounds are codified [here](https://github.com/aquarhead/protect-the-rabbit/blob/master/Makefile.toml#L10-L18).

I think it's possible that we integrate these extra LLVM tools, but I'd like to see your opinion first. Also I'd really like to understand what's in the `.text` section anyway...

Another potential issue is how to use multiple maps if `tc` only expects a single section, though it might not be an issue but I don't think I've tried it.

On a sidenote, I submitted a lightning talk on exactly this work for the eBPF summit, and it got accepted, I'd really appreciate it if you would like to see my draft (I need to prepare a recorded video before Friday).

### CODE REVIEW

**Comment by rsdy** [comment]
Hey, it's great to see this, thanks!
I'd be happy to review the talk draft, if you message me here or on Twitter, my DMs are open.

**Review by rsdy — APPROVED** [review]
Really good quality PR, I have no objections to merging this as is, if you're happy with it. Thanks a lot!

**Comment by alessandrod** [comment]
I think both issues can be fixed without incompatible changes to the current toolchain.

The `.text` section has to do with https://github.com/alessandrod/redbpf/blob/685c51862f58d89b399958e1cb126fa325fb4059/cargo-bpf/src/llvm.rs#L182. Since we have no way to provide the library info, and since we ask rustc to do the first step of the compilation for the host target triple, llvm ends up thinking that the target provides bcmp when it doesn't. So to make things work we inject our own bcmp (and other builtins), that end up in .text. I'm working on a workaround for this right now.

The map thing we just need to decide the API. Currently `#[map("foo")]` outputs an ELF section named "maps/foo". we could have `#[map(name="")]` or something to output just "maps".

**Comment by aquarhead** [comment]
Just remembered, I believe `tc` also supports attaching already loaded programs - which means it doesn't need to interpret the ELF file by itself - so maybe we can also just provide/extend our loader to load the program and maps and don't necessarily need to "fix" the ELF file?

**Comment by rsdy** [comment]
Let's move this loader discussion to #56 . I'm merging this. Thanks both!

**Pull request merged**
