### PR TITLE
Reduces bindgen child-deps + fixes clippy lints

### PR DESCRIPTION
**Pull request by kbknapp**
This PR is in two commits:

- Reducing compile time deps of `bindgen` by removing default features (these deps are not required by anything `redbpf` is doing)
- Fixes a bunch of clippy lints.

The commits have decent messages to explain the details.

Tests are currently failing on `master` so I wasn't able to check that, but all tests that pass on master still pass here. I also compiled against current stable and current nightly.

### CODE REVIEW

**Comment by rsdy** [comment]
This looks great, thanks! It breaks a few public APIs, so we'll definitely need a new minor version when we merge it, and most likely will break ingraind too. Let me run a few tests as well before merging!

**Comment by kbknapp** [comment]
> It breaks a few public APIs

I think the only spot the public API changes is in `bpf-sys` where a return goes from `Result<T, ()>` to `Option<T>`. I think it'd be fine to roll that change back until an eventual 2.0 as its just a pedantic change, there is nothing inherently *wrong* with `Result<T, ()>`, its just less idiomatic.

Let me know if you'd like me to roll that back :wink:

**Comment by rsdy** [comment]
@kbknapp That might be the best approach. I agree that the API is not idiomatic, although to be fair using `MaybeUninit` in specifically `uname()` would potentially give us a nicer implementation. If you roll back those changes, I can merge this quickly.

**Comment by kbknapp** [comment]
Sorry for the delay; with the holidays it took me a minute to sit down at a computer. I've rolled back those changes, but please do a double check and make sure I didn't miss any. Let me know if any additional changes are required.

**Comment by rsdy** [comment]
This looks great! Thanks a lot!

**Review by rsdy — APPROVED** [review]

**Pull request merged**
