### PR TITLE
Add examples

### PR DESCRIPTION
**Pull request by rhdxmr**
redbpf-examples is added for showing simple BPF programs which are not enough quality to be redbpf-tools. And it is expected that newbies can get to know what they can do with redbpf by studying code of redbpf-examples.

I am a newbie of redbpf and I hope this example code are helpful to other newbies.
And I anticipate that other users of redbpf can put their bpf programs into this example directory easily.

### CODE REVIEW

**Comment by rsdy** [comment]
I think I would prefer if this was in an `examples` folder, or simply part of `redbpf-tools`. Using `examples` gives us the benefit that cargo [is able to handle it straight from the command line](https://doc.rust-lang.org/cargo/commands/cargo-run.html#examples).

**Review by rsdy — CHANGES_REQUESTED** [review]
I think I would prefer if this was in an `examples` folder, or simply part of `redbpf-tools`. Using `examples` gives us the benefit that cargo [is able to handle it straight from the command line](https://doc.rust-lang.org/cargo/commands/cargo-run.html#examples).

**Comment by rhdxmr** [comment]
@rsdy OK I'll modify the PR to use `examples` Thanks,

**Review by rsdy — APPROVED** [review]

**Comment by rhdxmr** [comment]
hello @rsdy 
I changed redbpf-examples as examples and it is now available with cargo run --example
Can you review this?
Thanks,

**Pull request merged**
